### ISSUE TITLE
Introduce concepts before describing their behavior

### ISSUE THREAD

**Issue by db48x** [christianparpart/terminal-good-image-protocol#17]
It is likely that this isn’t intended, but some concepts are not properly introduced before the spec starts talking about the details of how they behave. For example, section 10.1.1 talks about what the Upload Image command does when the image is named, but this is the first mention that images _can_ be named anywhere in the spec.

**Comment by christianparpart** [comment]
Oh nice finding.

The spec's two main sections are "Semantics" (s. 10) and "Syntax" (s. 11). Semantics should have introduced everything in order and fully specified except how it looks like on the wire.

"Syntax" (section 11) fills the gap with how it looks like on the wire (actual VT sequences introduced or extended). 

Thanks for carefully reading through the draft :)

**Comment by christianparpart** [comment]
I've just added that as a `\subsection` into the Semantics section to introduce it all. I hope I did not miss anything. I'll be updating the preview branch soon so that it's also downloadable as PDF (the Github Actions "Summary" page for each action does contain them, too, in case you'd like to read it as PDF earlier).

Many thanks for pointing that out.
