### ISSUE TITLE
Introduce named resources

### ISSUE THREAD

**Issue by VoightKampff** [christianparpart/terminal-good-image-protocol#4]
- Add parameters to the upload image command - a string key and a version identifier. The terminal should reply with an int32 id for the image.
- Add command to query whether a named resource is stored in the pool. The reply should contain the image Id (int32) or -1 if not found and the version identifier.

**Comment by christianparpart** [comment]
Every command should by default be synchronous.

This semantics CAN be extended to optionally request a response from the terminal. I absolutely agree on that, I had that semantics in my initial draft, but I deleted that because I feared that this additional functionally would intimidate people away from adopting this protocol.

**Comment by jerch** [comment]
> Add command to query whether a named resource is stored in the pool.

Thats a clear nogo from my side, as it is a security nightmare - it makes it possible to obtain pool information by a later application from a previous one. If this later application runs under different privileges, hell might break loose, it allows fingerprinting into other user sessions.

I second the "synchronous" approach - a terminal should report as little as possible of its internal state to the application side. From application side it should be treated as data dumpster with not much further knowledge beside basic protocol limits/caps. This also means that the sequences should try to succeed most of the time in terms of output representation (i.e. if an image cannot be loaded, print a placeholder instead).
The application does not have to know whether it was shown successfully, instead should be able to anticipate the correctness of the output from the protocol limits/caps, i.e. an image within the storage limits will show up, maybe evicting older one (FIFO), an image bigger than the storage limits is expected to fail in showing its pixel data, but would still be treated correctly in covered text cells with a placeholder (or some other visual feedback).

**Comment by christianparpart** [comment]
Since we *do* have named resources (except for the query part), and these names are strings (not integers) with encouraging clients to use a FQDN-style notation (such as `.org.binutils.ls.ID123`, I think this problem is solved. Except for the query part that (if at all) could be added at any time later.
