### ISSUE TITLE
Evaluate compression for image data

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/terminal-good-image-protocol#5]
[Zstd](https://facebook.github.io/zstd/) is a compression algorithm that is fast both ways.

* Is it available for enough platforms so other parties will not be intimidated by requiring Zstd as part of this protocol?
* How can we make it play nice when embedding into DCS, OSC or APC?

**Comment by jerch** [comment]
I think we should not bother with transport compression at the sequence level. The terminal links either to local apps with insane throughput, or goes through some remote transport layer, that does already compression in some way. If SSH bothers enough, this should be implemented there.

Still I am concerned with your RGBA notion in the spec, imho thats not a good idea due to the high data pressure (even local). Imho we should stick with PNG for lossless in the beginning, and maybe add one lossy common format as well (JPEG?) This is still easy adoptable by anyone without getting the hands dirty with a GP compression algo thats not really image data optimized.

**Comment by christianparpart** [comment]
I agree here too. One side note I would like to add: headless terminals should not need to decode anything but treat the image data as binary blob. Only frontends need to be able to understand the actual format of the image data. Thanks for your input.
