### ISSUE TITLE
DCS vs OSC

### ISSUE THREAD

**Issue by jerch** [christianparpart/terminal-good-image-protocol#9]
I suggest to rethink the usage of DCS as the main sequence type. While I have no personal objections here (in fact I like DCS much more than OSC), broad support of DCS is really weak up to non existent in several kernel consoles. Sadly that is not likely to change soon, as those terminal interfaces are really slow moving.

An alternative might be a custom OSC sequence - support in general is much better across other emulators and prolly easier to integrate to several terminals as well.

Other types like APC are not worth to be considered, most terminals have no support for this or even will go bonkers (imho the biggest flaw in kitty's protocol).

**Comment by christianparpart** [comment]
I prefer DCS (Device Control Sequence) highly over OSC (Operating System Command), because -in fact- it's semantically more fitting to DCS than OSC.

I am aware of DCS/APC not being widely supported. Here are my thoughts:

* emulators not supporting DCS anytime soon will also most likely not support this image protocl (nor any other)
* even if upload/render/release sequences are DCS, you should always first query for support, which is a CSI sequence. Therefore the application would not send any DCS at all of the feature testing CSI sequence already failed
* I am still fine in agreeing on using OSC over DCS for that, even though the above would still hold true personally iff that helps adoption by emulators. But questions like these are one of the two reasons why I strictly split semantics from syntax in the draft spec, so we can focus on semantics independently and more focused without worrying about what sequence to use for these "functions".

**Comment by jerch** [comment]
> emulators not supporting DCS anytime soon will also most likely not support this image protocl (nor any other)

Yepp, very true.

> even if upload/render/release sequences are DCS, you should always first query for support, which is a CSI sequence. Therefore the application would not send any DCS at all of the feature testing CSI sequence already failed

Hmm well, this is also true, but kinda left the sloppy app devs out of the equation. This is not meant as finger-pointing - still we have somewhat a renaissance of more capable terminal interfaces in newer cmdline apps, but often with hard-coded sequences (as seen in some nodejs tools). I am not sure who to blame here - in the end it is those devs' problem ofc, but the terminal interface is such a tough beast with lousy and scattered docs, that TE devs get it sometimes wrong.

What I am trying to say - those newer apps give not much on "request TE caps first", they will just render those older terminals unusable (and image sequences carry very much payload by their nature, thus the output will go all bonkers).

OSC on the other hand has wider adoption already, and a well written parser would just skip/ignore an unknown function call. Imho this allows a less bumpy upgrade path for those outdated TEs, and less friction on app dev side.

Plz dont get me wrong, I am also in favour of DCS from a technical viewpoint, it is just a concern, that we cannot easily force the TE world to move on. Well, it kinda boils down to whether we take the risk to break with many other TEs or take the less bumpy road. I did not even decide for myself, whats better here, therefore I just what to raise that concern here so we can come to an informed decision in the end.

**Comment by christianparpart** [comment]
Please do not show at me for replying short. I agree and already changed that to OSC instead of DCS in the reference implementation. Tomorrow i want to bring the spec tex source files more up to date. Also, i feel like i have to thank you all (!) for the raised interest. I will try my best to help us all finding a good protocol spec that is best for all of us. :)

**Comment by PerBothner** [comment]
Another reason to prefer OSC over DCS is that the former has a larger "namespace": It is easier to reserve/standardize a new OSC number that to add the DCS or APC code letters.

It might make sense to define a protocol such that it an extension of the iTerm2 protocol, which uses OSC 1337.

**Comment by christianparpart** [comment]
> Another reason to prefer OSC over DCS is that the former has a larger "namespace": It is easier to reserve/standardize a new OSC number that to add the DCS or APC code letters.

I hereby officially give up on my ideal-world approach and will change the spec to `OSC` :-)

> It might make sense to define a protocol such that it an extension of the iTerm2 protocol, which uses OSC 1337.

I personally really dislike the whole OSC 1337 subnamespace, I think we also should not temper with the iTerm2 introduced code, as it should stay propriaty (Unless Jeorge Gnachman now chimes in and gives his thoughts on this? - I'm not sure if he's on Github, so I could not @/cc him here).

So reserving a new number for the GIP in the OSC namespace is fairly easy and I'll come up with a dummy and see how people will like it).

So I think, for now, I can close this ticket as "resolved".
